version: "3.7"

services:
    postgres_db:
        image: postgres:16
        restart: always
        shm_size: 128mb
        ports:
            - 5432:5432
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=very_good_password
            - POSTGRES_USER=user
            - POSTGRES_DB=resonate
    mongo_db:
        image: mongo:latest
        restart: always
        volumes:
            - mongo_db:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: not_really_a_pass

    resonate:
        build:
            context: .
            target: development
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3333:3333
        command: npm run start:api
        depends_on:
            - postgres_db
            - mongo_db
        environment:
            PORT: 3333
            ARBITRUM_RPC_URL: https://arb-mainnet.g.alchemy.com/v2/fmrqiiCFFjJ_nyF3ItEflVVJ3LF-HBz_
            DATABASE_URL: postgres://user:very_good_password@postgres_db:5432/resonate
            FANTOM_RPC_URL: https://twilight-delicate-wildflower.fantom.quiknode.pro/e17ae5b40af70a5e7db66cbf8b9ec7474893fdc3/
            MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/zOVFUzSEld1v_MuTOqGPYkTYttwBUrmF
            OPTIMISM_RPC_URL: https://opt-mainnet.g.alchemy.com/v2/ZKd9Q4Jm6JdtzHEPy_3wB77PnJqM7fvm
            POLYGON_RPC_URL: https://polygon-mainnet.g.alchemy.com/v2/XZF2U-6qLByJKH9OVsB8rflwSYaZRQaq
            PGDATABASE: resonate
            PGHOST: postgres_db
            PGPASSWORD: very_good_password
            PGPORT: 5432
            PGUSER: user
            AUTH_KEY: 3b6620a4-4427-4deb-9c6c-6d539974ff77

volumes:
    mongo_db:
        driver: local
